coverage_service: coveralls
ci_service: travis_ci
build_directory: build
binary_basename: Example
xcodeproj: Example/Example.xcodeproj
source_directory: XNGAPIClient
ignore:
  - Example/*
  - Example/Tests/*
